### ISSUE TITLE
'/home/pan/git/FlightSoftware/geomag_wrapper.mexa64' is not a MEX file

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/psim#184]
This error prevents running MATLAB-based HOOTL tests on Linux.

```
Pathfinder for Autonomous Navigation
Space Systems Design Studio, Cornell University
Console Software | Version 1.0

Opened connection to FlightController.
Running mission testcase EmptySimCase.
Running testcase initialization...
[TESTCASE] Starting testcase.
Configuring simulation (please be patient)...
Building with 'g++'.
Warning: You are using gcc version '9.3.0'. The version of gcc is not supported. The version currently supported with MEX is '6.3.x'. For a list of currently supported compilers see: https://www.mathworks.com/support/compilers/current_release.
> In generate_mex_code (line 8)
  In install (line 5)
Error using mex
'/home/pan/git/FlightSoftware/geomag_wrapper.mexa64' is not a MEX file. For more information, see <a href="matlab: helpview([docroot '/matlab/helptargets.map'],'ENOTMEX')">File is not a MEX file</a>.

Error in generate_mex_code (line 8)
mex("-R2018a", "CXXFLAGS=$CXXFLAGS -std=c++14", geomag_file, geomag_incl);

Error in install (line 5)
generate_mex_code();

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pan/git/FlightSoftware/ptest/__main__.py", line 29, in <module>
    sys.exit(main())
  File "/home/pan/git/FlightSoftware/ptest/__main__.py", line 26, in main
    return _command_map[sys.argv[1]].main(sys.argv[2:])
  File "/home/pan/git/FlightSoftware/ptest/run_simulation.py", line 269, in main
    simulation_run.start()
  File "/home/pan/git/FlightSoftware/ptest/run_simulation.py", line 55, in start
    self.sim.start()
  File "/home/pan/git/FlightSoftware/ptest/simulation.py", line 60, in start
    self.configure_sim()
  File "/home/pan/git/FlightSoftware/ptest/simulation.py", line 91, in configure_sim
    self.eng.install(nargout=0)
  File "/home/pan/git/FlightSoftware/venv/lib/python3.7/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/home/pan/git/FlightSoftware/venv/lib/python3.7/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/home/pan/git/FlightSoftware/venv/lib/python3.7/site-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError:
  File /home/pan/git/FlightSoftware/lib/common/psim/MATLAB/generate_mex_code.m, line 8, in generate_mex_code

  File /home/pan/git/FlightSoftware/lib/common/psim/MATLAB/install.m, line 5, in install
'/home/pan/git/FlightSoftware/geomag_wrapper.mexa64' is not a MEX file. For more information, see <a href="matlab: helpview([docroot '/matlab/helptargets.map'],'ENOTMEX')">File is not a MEX file</a>.
```

**Comment by stewartaslan** [comment]
Fixed by #185
